[package]
name = "spectral-raytracer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
cgmath = "0.18.0"
exr = "1.72.0"
rayon = "1.10.0"

[profile.dev]
opt-level = 3
target-cpu = "native"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
target-cpu = "native"